apps/owner/tsconfig.app.json
=> tsconfig 옵션 수정

apps/owner/src/pages/Request/RequestReview.tsx, apps/owner/src/pages/Request/StepByStep.tsx, apps/owner/src/pages/Request/Test.tsx, apps/owner/src/pages/Status/CompletedRequest.tsx, apps/owner/src/pages/Status/PendingRequest.tsx, apps/owner/src/pages/Status/Status.tsx, apps/owner/src/router.tsx, apps/owner/src/styles/sequenceAnimation.css, apps/owner/tailwind.config.js, packages/design-system/components/BorderContainer/BorderContainer.tsx, packages/design-system/components/CategoryTab/CategoryTab.tsx, packages/design-system/components/Header/Header.tsx
- 카테고리탭 부분 로직 수정하여 그냥 텀포넌트만 올려놓아도 애니메이션 적용되도록 구현함
- 헤더 부분 버튼 이 누랃되어 있는 곳이 있어 추가
ㄱㅅㅎㄴㄷ
=> 카테고리탭 수정, 헤더 수정, 견적요청 로직 대강완료

.github/workflows/storybook-gh-pages.yml
=> 스토리북 배포에서 yarn 버전 수정

apps/owner/src/pages/MainPage/MainPage.tsx, packages/design-system/components/Avatar/Avatar.tsx, packages/design-system/components/Icons/PlusIcon.tsx, packages/design-system/index.ts
- 아바타 컴포넌트 구현
- mode는 avatar, add, request로 구분되며 각각 반려견 프로필, 프로필 추가, 견적 재요청을 위한 컴포넌트입니다.
- 반려견 프로필로 사용하는 경우에만 name props에 반려견 이름을 작성하시면 됩니다.
- isActive는 활성화 상태 유무로 견적서 조회에서 사용하시면 됩니다.
=> 아바타 컴포넌트 구현

.github/workflows/storybook-gh-pages.yml, apps/storybook/.gitignore, apps/storybook/eslint.config.js, apps/storybook/package.json
=> 스토리북 스크립트 수정

apps/owner/src/pages/AddressTest/AddressTest.tsx, apps/owner/src/router.tsx, package.json, packages/design-system/components/Icons/MySearchIcon.tsx, packages/design-system/components/Input/Input.tsx, packages/design-system/components/InputAddress/InputAddress.tsx, packages/design-system/components/InputAddress/SearchAddress.tsx, packages/design-system/index.ts, packages/design-system/tsconfig.json, packages/design-system/utils/getAddress.ts, yarn.lock
- 주소 입력창 컴포넌트
- **props로 보내줄 수 있는 값 (추후 address state 추가 예정)**
1. label?: string;
- **사용예시**
- 테스트용 url : /address/test
```tsx
return (
<InputAddress label='주소' />
);
```
=> 주소 입력창 컴포넌트 구현

.github/workflows/storybook-gh-pages.yml, .gitignore, apps/storybook/.gitignore, apps/storybook/.storybook/main.ts, apps/storybook/eslint.config.js, apps/storybook/package.json, turbo.json
=> 스토리북 배포 github action 수정

apps/owner/src/App.tsx, apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx, packages/design-system/components/BottomTabBar/BottomTabBar.tsx, packages/design-system/components/Layout/Layout.tsx
=> layout padding 추가

apps/owner/src/pages/InputTest/InputTest.tsx, packages/design-system/components/FileUpload/ImageUpload.tsx, packages/design-system/components/FileUploader/ImageSlider.tsx, packages/design-system/components/FileUploader/ImageUploader.tsx, packages/design-system/components/FileUploader/ProfileImgUploader.tsx, yarn.lock
- 서버에서 받아온 기존 이미지 url 보이도록 수정
- 기존 이미지를 props로 보내줌 : initialImgList(ImageUploader 컴포넌트) / initialImageUrl(ProfileImgUploader 컴포넌트)
=> 이미지 업로드 수정

apps/owner/src/pages/Status/DetailPage.tsx, apps/owner/src/pages/Suggest/Suggest.tsx, apps/owner/src/pages/Suggest/TextEditor.tsx, apps/owner/src/styles/TextEditor.css, packages/design-system/components/Calendar/Calendar.tsx, packages/design-system/components/TimeSelect/TimeSelect.tsx
- 캘린더 디자인 수정
- 견적제안 부분 대부분 마무리
=> 캘린더 관련 수정 및 기타 수정

apps/designer/vite.config.ts
=> designer vite.config.js 수정

apps/owner/src/pages/Request/ProfileViewer.tsx, apps/owner/src/pages/Request/RequestReview.tsx, apps/owner/src/pages/Request/StepByStep.tsx, apps/owner/src/pages/Status/CompletedRequestUser.tsx, apps/owner/src/pages/Status/DetailDesigner.tsx, apps/owner/src/pages/Status/PendingRequestUser.tsx, apps/owner/src/pages/Status/RequestContainer.tsx, apps/owner/src/pages/Status/SuggestReview.tsx, apps/owner/src/pages/Suggest/Suggest.tsx, apps/owner/src/pages/Suggest/TextEditor.tsx, apps/owner/src/router.tsx, packages/design-system/components/Calendar/Calendar.tsx
=> 디테일페이지 ui 수정

apps/guardian/src/constants/routes.ts, apps/guardian/src/router.tsx
=> guardian 서비스 test 페이지 추가

apps/owner/src/pages/Request/ProfileViewer.tsx, apps/owner/src/pages/Request/Request.tsx, apps/owner/src/pages/Request/StepByStep.tsx, apps/owner/src/pages/Status/CompletedRequestDesigner.tsx, apps/owner/src/pages/Status/CompletedRequestUser.tsx, apps/owner/src/pages/Status/DetailDesigner.tsx, apps/owner/src/pages/Status/DetailPage.tsx, apps/owner/src/pages/Status/PendingRequestDesigner.tsx, apps/owner/src/pages/Status/PendingRequestReservation.tsx, apps/owner/src/pages/Status/PendingRequestUser.tsx, apps/owner/src/pages/Status/Status.tsx, apps/owner/src/pages/Status/SuggestReview.tsx, apps/owner/src/pages/Suggest/Suggest.tsx, packages/design-system/components/BorderContainer/BorderContainer.tsx
=> 레이아웃 대폭 수정

apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx, apps/owner/src/components/DesignerInfo/Designer.tsx, apps/owner/src/components/DesignerInfo/PremiumList.tsx, apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx, apps/owner/src/pages/MainPage/MainPage.tsx, apps/owner/src/pages/MainPage/SearchResultPage.tsx, packages/design-system/components/BottomTabBar/BottomTabBar.tsx, packages/design-system/components/CategoryTab/CategoryTab.tsx, packages/design-system/components/Input/Input.tsx, packages/design-system/components/InputAddress/InputAddress.tsx, packages/design-system/components/Progress/progress.tsx, packages/design-system/components/TextArea/TextArea.tsx
- 메인페이지 카테고리 사이즈 축소
- 메인페이지 디자이너 리스트 글자 사이즈 축소
- 하단 탭 바 글자 사이즈 및 상하패딩 축소
- 프로그래스 바 디자인 수정
- 인풋창 디자인 수정
=> design: 전체적인 디자인 수정

apps/designer/src/router.tsx, apps/owner/.gitignore, apps/owner/src/apis/login/getLogin.tsx, apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx, apps/owner/src/components/KakaoLoginBtn/KakaoLoginBtn.tsx, apps/owner/src/constants/queryKeys.ts, apps/owner/src/constants/routes.ts, apps/owner/src/hooks/queries/Alarm/usePostExample.ts, apps/owner/src/hooks/queries/Login/useGetLogin.ts, apps/owner/src/pages/CreateReviewPage/CreateReviewPage.tsx, apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx, apps/owner/src/pages/LoginPage/LoginContent.tsx, apps/owner/src/router.tsx, apps/owner/vite.config.ts, packages/shared/src/apis/APIFetch.ts, packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx, packages/shared/src/index.ts
=> 로그인 api 추가 및 예시코드 작성

apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx, packages/design-system/components/ServiceCheckBox/ServiceCheckBox.tsx
=> 디자이너앱  빌드 에러 수정

apps/owner/src/apis/searchDesigner/getSearchResult.ts, apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx, apps/owner/src/constants/queryKeys.ts, apps/owner/src/hooks/queries/DesignerList/useGetSearchDesigners.ts, apps/owner/src/hooks/queries/DesignerList/useGetTotalDesigners.ts, apps/owner/src/pages/MainPage/MainPage.tsx, apps/owner/src/pages/MainPage/SearchResultPage.tsx
- 메인페이지에서 디자이너 검색할 수 있는 api 연동 완료
=> 메인페이지 디자이너 검색 api 연동

apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx, apps/owner/src/router.tsx
- 로그인 여부 상관없이 모든 페이지 접근 가능하도록 임시설정
=> 로그인 여부 상관없이 모든 페이지 접근 가능하도록 임시설정

apps/owner/src/pages/DesignerProfilePage/components/Profile.tsx
=> 빌드 에러 수정: 사용하지 않는 변수 제거

apps/guardian/tsconfig.app.json
=> guardian tsconfig 수정

apps/guardian/src/pages/MainPage.tsx, apps/guardian/tsconfig.app.json
=> tsconfig 수정

.github/workflows/frontend-ci-cd.yml, apps/guardian/index.html
- workflow env 추가
- navermap submodule 추가
=> workflow env 추가 및 navermap submodule 추가

apps/designer/vite.config.ts, apps/guardian/vite.config.ts
=> vite.config base 추가

.github/workflows/frontend-ci-cd.yml, apps/guardian/tsconfig.app.json
=> github action workflow 수정

apps/owner/src/apis/imageUpload/postMultipleImageUpload.ts, apps/owner/src/hooks/queries/ImageUpload/useMultipleImageUpload.ts, apps/owner/src/pages/Request/Test.tsx
=> 다중이미지 업로드 api 

apps/designer/src/hooks/queries/Profile/useRegisterProfile.ts, apps/owner/src/apis/petProfile/registerPetProfile.ts, apps/owner/src/hooks/queries/PetProfile/useRegisterPetProfile.ts, apps/owner/src/pages/AddPetProfilePage/AddPetProfilePage.tsx, apps/owner/src/pages/KakaoCallback/KakaoCallback.tsx, yarn.lock
=> 반려견 등록 api 연동

apps/owner/src/components/DesignerInfo/Designer.tsx, apps/owner/src/components/MainCategoryTab/MainCategoryTab.tsx
- 메인페이지에서 디자이너 정보 클릭시 프로필 상세 페이지로 연결
=> 메인페이지에서 디자이너 프로필로 연결

apps/designer/src/apis/request/putSuggest.ts, apps/designer/src/components/BottomTabBar/DesignerBottomTabBar.tsx, apps/designer/src/hooks/queries/ImageUpload/useMultipleImageUpload.ts, apps/designer/src/hooks/queries/Request/usePostDetailPage.ts, apps/designer/src/hooks/queries/Request/usePutSuggest.ts, apps/designer/src/pages/StatusPage/DetailPage.tsx, apps/designer/src/pages/SuggestPage/SuggestPage.tsx, apps/owner/src/apis/payment/getPaymentOrderId.ts, apps/owner/src/apis/payment/postPaymentProcess.ts, apps/owner/src/apis/payment/postReservationEstimate.ts, apps/owner/src/apis/suggest/postSuggestRequest.ts, apps/owner/src/components/BottomTabBar/OwnerBottomTabBar.tsx, apps/owner/src/hooks/queries/Payment/useGetPaymentDetail.ts, apps/owner/src/hooks/queries/Payment/useGetPaymentProcess.ts, apps/owner/src/hooks/queries/Payment/usePostReservationEstimate.ts, apps/owner/src/hooks/queries/Request/useGetPendingRequests.ts, apps/owner/src/hooks/queries/Request/useGetUserCompletedRequests.ts, apps/owner/src/pages/DirectRequestPage/DirectRequestPage.tsx, apps/owner/src/pages/PaymentPage/PaymentPage.tsx, apps/owner/src/pages/PaymentPage/PaymentSuccessPage.tsx, apps/owner/src/pages/Request/ProfileViewer.tsx, apps/owner/src/pages/Request/StepByStep.tsx, apps/owner/src/pages/Status/DetailPage.tsx, apps/owner/src/pages/Status/PendingRequestUser.tsx, apps/owner/src/pages/Status/Status.tsx, apps/owner/src/pages/Status/SuggestReview.tsx, apps/owner/src/stores/usePaymentStore.ts, apps/owner/src/stores/useReservationStoreOne.ts, apps/owner/src/stores/useReservationStoreTwo.ts
=> 견적요청 및 예약 초안

apps/owner/src/pages/EditPetProfilePage/EditPetProfilePage.tsx, packages/design-system/components/Avatar/Avatar.tsx, packages/design-system/components/ProfileImage/UserProfileImage.tsx
=> 반려견 수정 api 연동

apps/designer/src/apis/Profile/updateProfile.ts, apps/designer/src/components/BottomTabBar/DesignerBottomTabBar.tsx, apps/designer/src/pages/EditDesignerProfilePage/EditDesignerProfilePage.tsx, apps/designer/src/pages/EditDesignerProfilePage/components/CertificationUploader.tsx, apps/designer/src/pages/MyPage/components/Profile.tsx, apps/designer/src/pages/ReservationPage/ReservationPage.tsx, packages/design-system/components/ServiceCheckBox/ServiceCheckBox.tsx
- 디자이너 프로필 수정 api 연동
- 디자이너 프로필 삭제 위한 모달 추가
- 현재 경로에 따라 예약 페이지 헤더 변경되도록 수정
=> 디자이너 프로필 수정 api 연동

packages/shared/src/apis/APIFetch.ts, packages/shared/src/components/RouterErrorFallback/RouterErrorFallback.tsx
* feat: 로그인 에러 처리 추가
- description
=> v1.1.3 Release

apps/owner/src/components/NaverMap/NaverSearchDesignerMap.tsx
* feat: 가디언 지도 디자이너와 보호자 위치 추가
* feat: 보호자 네이버 지도 자신과 디자이너 좌표 추가
* fix: 지도에서 디자이너 프로필 이동 수정
- description
=> v1.1.5 Release
